name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9","3.10","3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install
          
      - name: Lint with ruff
        run: make lint
      
      - name: Test with pytest
        run: make test
          
      - name: Format with black
        run: make format
      - name: Update README badges
        run: |
          echo "## Build Status" > README.md
          echo "" >> README.md
          echo "Python 3.9: [![Build Status](https://github.com/minlingz/706miniP4/workflows/Python%203.9/badge.svg)](https://github.com/minlingz/706miniP4/actions?query=workflow%3A%22Python+3.9%22)" >> README.md
          echo "Python 3.10: [![Build Status](https://github.com/minlingz/706miniP4/workflows/Python%203.10/badge.svg)](https://github.com/minlingz/706miniP4/actions?query=workflow%3A%22Python+3.10%22)" >> README.md
          echo "Python 3.11: [![Build Status](https://github.com/minlingz/706miniP4/workflows/Python%203.11/badge.svg)](https://github.com/minlingz/706miniP4/actions?query=workflow%3A%22Python+3.11%22)" >> README.md